name: 'test_dbt'
version: '1.0.0'
config-version: 2

profile: 'test_dbt'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
og-path: /tmp/logs
packages-install-path: /tmp/dbt_packages/

target-path: /tmp/target/
clean-targets:
  - "target"
  - "dbt_packages"

models:
  test_dbt:
    example:
      +materialized: view